### ISSUE TITLE
mediacrush's slowness blocks the rest of the application from loading

### ISSUE THREAD

**Issue by evaryont** [Thristhart/kitchensync#19]
so that happens, and it's sad because people (durelle and me at first, before I realized) are thinking kitchensync is slow when instead the problem is the browser is blocked waiting for mediacru.sh's script to load.

Should be as simple as setting the async attribute on the `<script>` element, no?

**Comment by Thristhart** [comment]
This isn't actually a fix, but since mediacrush is down this solves the problem anyway.

**Comment by evaryont** [comment]
We should probably remove most mediacrush related stuff in the spirit of YAGNI -- no one uses it, why keep the code around?

**Comment by Thristhart** [comment]
I intend to replace it with perhaps a limited local upload, or a different media upload service. If you feel like submitting a pull request simply removing it, I will merge it, otherwise I'll leave it until I've replaced the functionality.
